"""added user new field aut

Revision ID: 05b515ef5e9e
Revises: f4dfed3294f2
Create Date: 2025-04-21 19:12:59.808486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05b515ef5e9e'
down_revision = 'f4dfed3294f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_Confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_column('isConfirmed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isConfirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_Confirmed')

    # ### end Alembic commands ###
