"""change date-fields

Revision ID: 4a9142bd087a
Revises: 7fbf471b31ea
Create Date: 2025-04-22 20:55:11.205797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9142bd087a'
down_revision = '7fbf471b31ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
