"""change length description Product v2

Revision ID: 5f4298a883f5
Revises: 3b5123fe4f0a
Create Date: 2025-04-22 03:58:27.903595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f4298a883f5'
down_revision = '3b5123fe4f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=700),
               type_=sa.String(length=1250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=1250),
               type_=mysql.VARCHAR(length=700),
               existing_nullable=False)

    # ### end Alembic commands ###
