"""change date-fields

Revision ID: 7fbf471b31ea
Revises: 76e44b8f2620
Create Date: 2025-04-22 20:53:26.727098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fbf471b31ea'
down_revision = '76e44b8f2620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', mysql.DATETIME(), nullable=False))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', mysql.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
