"""Added fields for user email verif

Revision ID: ac0542066b3f
Revises: d91ffc404110
Create Date: 2025-04-21 17:32:53.252059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0542066b3f'
down_revision = 'd91ffc404110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isConfirmed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('code_confirm_email', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('code_confirm_email')
        batch_op.drop_column('isConfirmed')

    # ### end Alembic commands ###
