"""change fields from OrderProducts

Revision ID: c8e5e1a50afc
Revises: 4a9142bd087a
Create Date: 2025-04-23 09:00:56.360336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8e5e1a50afc'
down_revision = '4a9142bd087a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('size_info',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.alter_column('size_info',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('size',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
