"""change relationship for PRODUCT with similar_product

Revision ID: d670f030911d
Revises: bea3ff230438
Create Date: 2025-04-22 03:17:20.075578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd670f030911d'
down_revision = 'bea3ff230438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_ibfk_2', type_='foreignkey')
        batch_op.drop_column('products_similar_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('products_similar_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('product_ibfk_2', 'product_similar', ['products_similar_id'], ['id'])

    # ### end Alembic commands ###
