"""Change null parameters user

Revision ID: d91ffc404110
Revises: d9540e0ef962
Create Date: 2025-04-21 17:02:43.153626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd91ffc404110'
down_revision = 'd9540e0ef962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sur_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sur_name', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
