"""Change null parameters user

Revision ID: d9540e0ef962
Revises: a4f0174a0d45
Create Date: 2025-04-21 16:50:23.946186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9540e0ef962'
down_revision = 'a4f0174a0d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('sur_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('region',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('number_delivery',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('number_delivery',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('region',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('sur_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
