"""change sizes from PRODUCT

Revision ID: e9ea18ffece7
Revises: d670f030911d
Create Date: 2025-04-22 03:46:02.215516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9ea18ffece7'
down_revision = 'd670f030911d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sizes', sa.JSON(), nullable=True))
        batch_op.drop_column('size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('sizes')

    # ### end Alembic commands ###
