"""change USER field number_delivery str

Revision ID: fc7b5cd5952f
Revises: 05b515ef5e9e
Create Date: 2025-04-21 23:09:00.595636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc7b5cd5952f'
down_revision = '05b515ef5e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('number_delivery',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('number_delivery',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
